home_dir: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/asl_digits_recog/src
openpose: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/openpose

labels: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F, G, H, I, J,
  K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, -1

num_classes: 36
hand_thresh: 0.5
sign_thresh: 0.5
video_src: 0

im_width: 640
im_height: 480

batch_size: 32
ckpt_dir: checkpoints/ckpt_alphabets
weights: ckpt_alphabets_f
log_dir: logs/alphabets/test


