home_dir: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/asl_digits_recog/src
train_dir: data/data_alphabets/tfrecord
test_dir: data/data_alphabets/tfrecord

num_classes: 36
num_epochs: 50

train_batch_size: 32
test_batch_size: 32

base_lr: 0.1
steps: [20, 40]

save_result: True
result_name: ckpt_alphabets_f
clear_ckpt: True
log_dir: logs/alphabets/train
ckpt_dir: checkpoints/ckpt_alphabets
ckpt_freq: 50


