home_dir: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/asl_digits_recog/src
dataset_dir: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/asl_digits_recog/dataset/sldd/Dataset

work_dir: data

phases:
  skeleton,
  split,
  normalize,
  tfrecord

skeleton:
  input_dir: dataset_dir
  output_dir: ./skeleton
  openpose: /home/rodneygracian/Desktop/Rod/research/projects/asl/GCN/openpose

split:
  input_dir: ./skeleton
  output_dir: ./split
  test: 20
  seed: 2

normalize:
  input_dir: ./split
  output_dir: ./normalized

tfrecord:
  input_dir: ./normalized
  output_dir: ./tfrecord

log_dir: logs
